# Simple methods to create tensors


In [1]:
import torch as t

In [2]:
t.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [4]:
t.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
t.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:

t.rand(2,3)

tensor([[0.1516, 0.4797, 0.4367],
        [0.2781, 0.6275, 0.1836]])

In [7]:
a=t.tensor([[1,2,3],[4,5,6]])
type(a)

torch.Tensor

In [10]:
t.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [12]:
#use of seed
# for reproducibility of same random numbers
t.manual_seed(100)
t.rand(2,3) 


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

same result for the seed 100

In [13]:
t.manual_seed(100)
t.rand(2,3) 

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
# different ways to create tensors

#arange 
print(t.arange(1,10,3))

#linspace
print(t.linspace(1,10,5))

#eye identity matrix
print(t.eye(4))


#full
print(t.full((2,3),2))


tensor([1, 4, 7])
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[2, 2, 2],
        [2, 2, 2]])


# Tensor shapes


In [18]:
x=t.tensor([[1,2,3],[4,5,6]])
#shape of tensor
print(x.shape)

torch.Size([2, 3])


In [19]:
t.empty_like(x)

tensor([[5820729462384,             0,             0],
        [            0,             0,             0]])

In [26]:
t.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
t.rand_like(x,dtype=t.float)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [29]:
x.dtype

torch.int64

# Mathematical Operation on tensors

1.Scalar Operations

In [30]:
x=t.tensor([[1,2,3],[4,5,6]])

In [38]:
#addition
print("addition of scalar  on x is\n ",x+2)

#substraction
print("substraction of scalar  on x is\n ",x-2)

#multiplication
print("multiplication of scalar on x is\n ",x*10)

#division
print("division of scalar  on x is \n",x/5)

#mod
print("modulus of scalar  on x is \n",x%3)

#power
print("power of scalar  on x is\n ",x**3)    

addition of scalar  on x is
  tensor([[3, 4, 5],
        [6, 7, 8]])
substraction of scalar  on x is
  tensor([[-1,  0,  1],
        [ 2,  3,  4]])
multiplication of scalar on x is
  tensor([[10, 20, 30],
        [40, 50, 60]])
division of scalar  on x is 
 tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])
modulus of scalar  on x is 
 tensor([[1, 2, 0],
        [1, 2, 0]])
power of scalar  on x is
  tensor([[  1,   8,  27],
        [ 64, 125, 216]])


In [40]:
# matematical operations on 2 tensors
y=t.tensor([[1,2,3],[4,5,6]])

#addition
print("addition of two tensors is\n ",x+y)

#substraction
print("substraction of two tensors is\n ",x-y)

#multiplication
print("multiplication of two tensors is\n ",x*y)

#division
print("division of two tensors is\n ",x/y)

#mod
print("modulus of two tensors is\n ",x%y)

#power
print("power of two tensors is\n ",x**y)





addition of two tensors is
  tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
substraction of two tensors is
  tensor([[0, 0, 0],
        [0, 0, 0]])
multiplication of two tensors is
  tensor([[ 1,  4,  9],
        [16, 25, 36]])
division of two tensors is
  tensor([[1., 1., 1.],
        [1., 1., 1.]])
modulus of two tensors is
  tensor([[0, 0, 0],
        [0, 0, 0]])
power of two tensors is
  tensor([[    1,     4,    27],
        [  256,  3125, 46656]])


In [43]:
x=t.rand(3,3)

# abs
t.abs(x)

# ceil
t.ceil(x)

# floor
# t.floor(x)



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

3. Reduction Operations

In [48]:
e=t.randint(size=(3,3),low=1,high=10,dtype=t.float)
e

tensor([[4., 1., 3.],
        [7., 2., 2.],
        [8., 4., 1.]])

In [49]:
t.sum(e)

#sum along dimension
t.sum(e,dim=0)

t.sum(e,dim=1)

tensor([ 8., 11., 13.])

In [50]:
t.mean(e)

tensor(3.5556)

In [52]:
t.prod(e)

tensor(10752.)

In [53]:
print("Variance of e:", t.var(e))
print("Standard deviation of e:", t.std(e))
print("Index of minimum value in e:", t.argmin(e))
print("Index of maximum value in e:", t.argmax(e))

Variance of e: tensor(6.2778)
Standard deviation of e: tensor(2.5055)
Index of minimum value in e: tensor(1)
Index of maximum value in e: tensor(6)


# Matrix operation on tensors


In [54]:
matrix1=t.ones(2,3)
matrix2=t.ones(3,2)

# Matrix multiplication
print("Matrix multiplication of matrix1 and matrix2 is\n", t.matmul(matrix1, matrix2))

Matrix multiplication of matrix1 and matrix2 is
 tensor([[3., 3.],
        [3., 3.]])


In [55]:
# dot product
print("Dot product of matrix1 and matrix2 is\n", t.dot(matrix1.flatten(), matrix2.flatten()))

Dot product of matrix1 and matrix2 is
 tensor(6.)


In [56]:
#transpose
print("Transpose of matrix1 is\n", t.transpose(matrix1,0,1))

Transpose of matrix1 is
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [60]:
# determinant
matrix1 = t.ones(2, 2)
print("determinant of matrix1 is\n", t.det(matrix1))

determinant of matrix1 is
 tensor(0.)


# Special Functions

In [62]:
k=t.rand(3,3)

In [63]:
#log
print("Natural logarithm of k is\n", t.log(k))

Natural logarithm of k is
 tensor([[-3.0935, -0.0204, -0.5892],
        [-0.3757, -0.7092, -2.5929],
        [-0.0403, -1.1175, -4.5800]])


In [64]:
# exponential
print("Exponential of k is\n", t.exp(k))

Exponential of k is
 tensor([[1.0464, 2.6638, 1.7416],
        [1.9873, 1.6356, 1.0777],
        [2.6130, 1.3869, 1.0103]])


In [65]:
#softmax
print("Softmax of k is\n", t.softmax(k, dim=0))

Softmax of k is
 tensor([[0.1853, 0.4685, 0.4548],
        [0.3519, 0.2876, 0.2814],
        [0.4627, 0.2439, 0.2638]])


In [67]:
# relu
print("ReLU of k is\n", t.relu(k))

ReLU of k is
 tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748],
        [0.9605, 0.3271, 0.0103]])


# Inplace operations

In [68]:
m=t.rand(3,3)
n=t.rand(3,3)

In [69]:
m.add_(n)  # In-place addition
print("In-place addition of m and n is\n", m)

In-place addition of m and n is
 tensor([[1.0013, 0.4635, 0.5335],
        [1.1034, 1.6854, 0.3791],
        [0.8350, 0.8259, 1.3169]])


In [70]:
m.relu_()  # In-place ReLU
print("In-place ReLU of m is\n", m)

In-place ReLU of m is
 tensor([[1.0013, 0.4635, 0.5335],
        [1.1034, 1.6854, 0.3791],
        [0.8350, 0.8259, 1.3169]])


# copy a tensor

In [77]:
a= t.rand(3,3)
a

tensor([[0.8993, 0.2732, 0.3397],
        [0.1879, 0.5534, 0.2682],
        [0.9556, 0.9761, 0.5934]])

In [78]:
b=a

In [79]:
b

tensor([[0.8993, 0.2732, 0.3397],
        [0.1879, 0.5534, 0.2682],
        [0.9556, 0.9761, 0.5934]])

id of tensor depict the logical address of that tensor in the memory 

In [81]:
print("id of a is ",id(a))
print("id of b is ",id(b))

if id(a) == id(b):
    print("a and b are the same object")

id of a is  1667116812240
id of b is  1667116812240
a and b are the same object


In [82]:
# copying using clone
b = a.clone()
print("id of a after cloning is ", id(a))
print("id of b after cloning is ", id(b))   



id of a after cloning is  1667116812240
id of b after cloning is  1667107301008


# Tensor reshaping 

In [86]:
ten=t.ones(4,4)
ten

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [89]:
ten.reshape(4,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [87]:
ten.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## squeeze and unsqueeze in matrix 

In [91]:
#unsqueeze and squeeze
ten.unsqueeze(0).shape  # Adds a dimension at index 

torch.Size([1, 4, 4])

In [92]:
#squeeze
ten.unsqueeze(0).squeeze(0).shape  # Removes the dimension at index

torch.Size([4, 4])

# Tensor Operation on GPU ( if available)

In [83]:
t.cuda.is_available()

False

# Pytorch and Numpy

In [93]:
arr=t.rand(3,3)
arr

tensor([[0.9127, 0.6818, 0.1953],
        [0.9991, 0.1133, 0.0135],
        [0.1450, 0.7819, 0.3134]])

In [94]:
import numpy as np
arr_np = arr.numpy()  # ConvertPyTorch tensor to NumPy array
print("NumPy array:\n", arr_np)

NumPy array:
 [[0.9126876  0.681768   0.19533807]
 [0.9990713  0.11334324 0.01352   ]
 [0.1450094  0.78194916 0.3133915 ]]


In [96]:
type(arr_np)

numpy.ndarray

In [99]:
# ndarray to tensor
arr_back = t.from_numpy(arr_np)  # Convert NumPy array back to PyTorch
arr_back

tensor([[0.9127, 0.6818, 0.1953],
        [0.9991, 0.1133, 0.0135],
        [0.1450, 0.7819, 0.3134]])