# Autograd - automatic gradient calcualtion module in pytorch 

Gradient/derivative of the function with respect to x calculated using simple autograd function calls

In [1]:
import torch 

In [5]:
x = torch.tensor([6.0], requires_grad=True)
y = x ** 2


In [6]:
y.backward()  # Compute the gradient
print(x.grad)  # Print the gradient of x

tensor([12.])


Now composite function and its gradients

In [13]:
x=torch.tensor([4.0], requires_grad=True)
y=x**2
z=torch.sin(y)

In [9]:
x

tensor([6.], requires_grad=True)

In [10]:
y

tensor([36.], grad_fn=<PowBackward0>)

In [11]:
z

tensor([-0.9918], grad_fn=<SinBackward0>)

In [14]:
z.backward()  # Compute the gradient of z with respect to x
print(x.grad)  # Print the gradient of x after the backward pass

tensor([-7.6613])


# Simple neural network using pytorch with autograd for gradient calculations

Manual method for simple NN

In [26]:
x=torch.tensor([6.7], requires_grad=True)
y=torch.tensor([0.0], requires_grad=True)

# w- weights
w=torch.tensor([1.0], requires_grad=True)

# b- bias
b=torch.tensor([0.0], requires_grad=True)

z=w *x +b

y_pred=torch.sigmoid(z)

loss=(y_pred - y)  


Using Autograd for simple NN calculations

In [30]:
loss.backward()  # Compute the gradient of loss with respect to w and b
print(w.grad, b.grad)  # Print the gradients of w and b after the backward

tensor([0.0082]) tensor([0.0012])


# Applying autograd on the multiple values

In [33]:
x=torch.tensor([1.0,3.0,5.0], requires_grad=True)

In [34]:
y=(x**2).mean()

In [35]:
y.backward()  # Compute the gradient
print(x.grad)  # Print the gradient of x

tensor([0.6667, 2.0000, 3.3333])


# Clearing gradients

In [60]:
x=torch.tensor([2.0], requires_grad=True)
y=x**2

In [61]:
y.backward()  # Compute the gradient
print(x.grad)  # Print the gradient of x

tensor([4.])


Gradient accumalation ?

In [62]:
# run again the backward pass
x.grad.zero_()  # Clear the gradients
y.backward()  # Compute the gradient again

print(x.grad)  # Print the gradient of x again

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

# Stop the gradient calculation during the backward pass at time of prediction

In [71]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x ** 2 

In [72]:
x

tensor([1., 2., 3.], requires_grad=True)

In [73]:
x.requires_grad_(False)  # Stop tracking gradients for x
y=x**2
x

tensor([1., 2., 3.])

tensor([1., 2., 3.])

detach

In [79]:
x=torch.tensor([6.7], requires_grad=True)
x
y=x**2

In [81]:
z=x.detach()  # Detach x from the computation graph
print(z.requires_grad)  # Check if z requires gradients (should be False)

False


In [82]:
z

tensor([6.7000])

In [80]:
y.backward()  # Compute the gradient
print(x.grad)  # Print the gradient of x after detaching

tensor([13.4000])


In [ ]:
y1=z**2
y1.backward()  # Compute the gradient of y1 with respect to z

no grad function 

In [84]:
with torch.no_grad():
    y = x ** 2  # This will not track gradients
    print(y.requires_grad)  # Should be False

False
